/**
 * Shohoz / Bangladesh Railway PDF Custom Font Decoder & Normalizer
 *
 * Bangladesh Railway e-tickets (generated by Shohoz / Synesis) use a legacy
 * 8-bit / PUA TrueType font where Bengali conjuncts (যুক্তবর্ণ) and visual vowel
 * signs (like visual e-kar \uE04E and ref \uE04D) are encoded in the Private Use
 * Area (PUA) \uE000-\uF8FF.
 *
 * This normalizer converts these PUA characters and reorders visual signs into
 * standard Unicode Bengali characters that render cleanly in any modern browser
 * and PDF viewer.
 */

const PUA_DIRECT_MAP: Record<string, string> = {
  '\uE0BF': 'ভ্র', // ভ্র
  '\uE0AE': 'ন্য', // ন্য
  '\uE0B3': 'প্র', // প্র
  '\uE0C3': 'ম্ব', // ম্ব
  '\uE058': 'ক্ষ', // ক্ষ
  '\uE07F': 'ট্র', // ট্র
  '\uE093': 'ত্র', // ত্র
  '\uE0E8': 'স্ত', // স্ত
  '\uE0C0': 'ম্ন', // ম্ন
  '\uE04A': '্য',  // য-ফলা
  '\uE111': 'দ্রু', // দ্রু
  '\uE053': 'ক্স', // ক্স
  '\uE0C4': 'ম্ভ', // ম্ভ
  '\uE0E7': 'স্ট', // স্ট
  '\uE0A1': 'ন্ত', // ন্ত
  '\uE0D7': 'শ্র', // শ্র
  '\uE0AF': 'প্ত', // প্ত
  '\uE0E5': 'স্ক', // স্ক
  '\uE103': 'শু', // শু
  '\uE055': 'ক্লা', // ক্লা
  '\uE056': 'ক্ত', // ক্ত
  '\uE100': 'রু', // রু
  '\uE013': 'ন্ট', // ন্ট
  '\uE057': 'ক্র', // ক্র
  '\uE068': 'ঙ্খ', // ঙ্খ
  '\uE098': 'দ্র', // দ্র
  '\uE123': 'কু', // কু
  '\uE0FF': 'সু', // সু
  '\uE0C5': 'ন্দ', // ন্দ
  '\uE0B0': 'ম্প', // ম্প
  '\uE0C7': 'ল্ল', // ল্ল
  '\uE0A2': 'ন্থ', // ন্থ
};

export function decodeBengaliPua(text: string): string {
  if (!text) return '';

  // Check if string contains any PUA characters \uE000-\uF8FF
  let hasPua = false;
  for (let i = 0; i < text.length; i++) {
    const code = text.charCodeAt(i);
    if (code >= 0xe000 && code <= 0xf8ff) {
      hasPua = true;
      break;
    }
  }

  if (!hasPua) {
    return text;
  }

  let result = text;

  // 1. Direct conjunct substitutions
  for (const [pua, uni] of Object.entries(PUA_DIRECT_MAP)) {
    result = result.replaceAll(pua, uni);
  }

  // 2. Handle Shohoz ref \uE04D placed AFTER the consonant (e.g. বিণত -> বর্ণিত, চাজ -> চার্জ)
  result = result.replace(/([ক-হড়-য়](?:্[ক-হড়-য়])*)([া-ৌ]?)\uE04D/g, 'র্$1$2');

  // 3. Handle visual e-kar \uE04E placed BEFORE the consonant / conjunct
  // e.g. \uE04E + Consonant + \u09BE -> Consonant + \u09CB (o-kar: শো, কো, মো, যো, হো)
  // e.g. \uE04E + Consonant -> Consonant + \u09C7 (e-kar: রে, দে, খে, থে, চে, শে, ট্রে)
  result = result.replace(
    /\uE04E([ক-হড়-য়](?:্[ক-হড়-য়])*)([া-ৌ]?)/g,
    (_match, cons, vowel) => {
      if (vowel === 'া') {
        return cons + 'ো';
      }
      return cons + 'ে' + vowel;
    }
  );

  // 4. Clean up any loose remaining PUA markers
  result = result.replaceAll('\uE04E', 'ে');
  result = result.replaceAll('\uE04D', 'র্');

  // Strip any remaining unmapped PUA code points
  result = result.replace(/[\uE000-\uF8FF]/g, '');

  return result;
}
